spring:
  application:
    name: stock-service
server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8083/eureka
  instance:
    hostname: localhost
